### ISSUE TITLE
How to download  audiostock dataset?

### ISSUE THREAD

**Issue by yangdongchao** [LAION-AI/audio-dataset#79]
Hi, I want to ask how to download Epidemic Sound dataset. Following the link in the audiostock  csv file, e.g. https://audiostock.net/audio/1111457/play , I find that I can download it by Windows browser, but it cannot used on linux system.

**Comment by YuchenHui22314** [comment]
Wget works for me, on my ubuntu 18.04. Try `wget https://audiostock.net/audio/1111457/play`. Then you can write download scripts based on wget. Thank you!

**Comment by YawYoung** [comment]
Hey, where did you find the audiostock_meta.csv, thanks ~!
