### ISSUE TITLE
How to download Freesound?

### ISSUE THREAD

**Issue by yangdongchao** [LAION-AI/audio-dataset#80]
Hi, can you share some ways to download Freesound?  e.g. How to use Linux scripts to download these audio.

**Comment by YuchenHui22314** [comment]
Hi! Maybe you could refer to command line tools like "wget" to write a script in python/bash.

**Comment by wwfcnu** [comment]
> Hi! Maybe you could refer to command line tools like "wget" to write a script in python/bash.

需要认证
